name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore --version-suffix ${{ github.run_id }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack Nuget
      run: dotnet pack DevPack/DevPack.csproj --output nuget-packages --configuration Release
    - name: Publish Nuget
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

